### ISSUE TITLE
Update README to be more clear on prop naming expectations

### ISSUE THREAD

**Issue by QSissler** [learn-co-curriculum/react-hooks-component-props-mini-project#13]
### Canvas Link

https://learning.flatironschool.com/courses/5842/assignments/214265

### Concern

In the deliverables, the expected name of the prop is italicized but I think it should be made more clear that they need to name the props correctly or they will not pass the tests. For example, change the first deliverable from 
```an <h1> with the _name_ of the blog, passed as a prop```  to
```an <h1> with the name of the blog, passed as a prop called name```

It is currently not clear enough and the error messages that are returned from learn test when their code works but they're just naming their props incorrectly is not helpful to the student. I.E.: I changed the prop name "posts" to "articles" (Which I have seen multiple students do) but this is the error they get from learn test:
<img width="885" alt="Screen Shot 2023-01-30 at 4 54 39 PM" src="https://user-images.githubusercontent.com/81705554/215603960-05408b31-4f6c-446f-adcc-49d2b0eab002.png">
This is confusing for students because their articles are rendering just fine but the test is not passing. It is difficult for students to look at this error and understand that they just need to rename articles to posts to get their tests passing.

### Additional Context

Since codegrade will require all tests to pass before they can submit the assignment, I highly recommend making this change before phase two when codegrade is live with students.

**Comment by jlboba** [comment]
Hello, thank you for your feedback! 

I agree and see how students can be, and have been, confused by this wording. I went ahead and updated all the relevant deliverables to be more clear about the prop naming. If I missed any, or if it's still not clear, please let me know. 

Thank you again!
