### ISSUE TITLE
Package.json issue

### ISSUE THREAD

**Issue by bbissette3** [learn-co-curriculum/react-hooks-component-props-mini-project#16]
### Canvas Link

https://learning.flatironschool.com/courses/6273/assignments/232346?module_item_id=544471

### Concern

These lines in package.json are the incorrect syntax and cause the test not to run .

 "jest": {
    "transform": {
      "^.+\\.js$": "babel-jest",
      "^.+\\.svg$": "jest-svg-transformer"
    }
  },

### Additional Context

Instructor Antonio is DOPE

### Suggested Changes

removing the above lines causes the test to run properly.

**Comment by QSissler** [comment]
Just had a student come in with the same issue.. When running npm test they are getting an Invalid transformer module error.

**Comment by l-stephen** [comment]
I also had a student come to me with this issue, we managed to resolve it by accessing the file located at react-hooks-component-props-mini-project/node_modules/jest-svg-transformer/lib/index.js and modifying line 4. We changed "exports.process = process_1.default" to "module.exports = {process: process_1.default}."

**Comment by lizbur10** [comment]
Hello all! The problematic lines have been removed from the package.json file, so I'm going to go ahead and close this issue. Thanks for contributing to the Flatiron School curriculum 💙
