### ISSUE TITLE
Typo of props for ArticleList

### ISSUE THREAD

**Issue by IguanasEverywhere** [learn-co-curriculum/react-hooks-component-props-mini-project#19]
### Canvas Link

https://learning.flatironschool.com/courses/6383/assignments/235196?module_item_id=551844

### Concern

In the instructions for ArticleList, it is stated that the props passed down to ArticleList will be `post` (singular): an array of Article components (one component for each post passed down as a prop called `post` to `ArticleList`).

However, the tests for this lab make clear that ArticleTest will be tested with a prop called `posts` (plural):
```
test("renders a <main> element", () => {
  const { container } = render(<ArticleList posts={posts} />);
  expect(container.querySelector("main")).toBeInTheDocument();
});
```
Given that the prop is an array, the plural form makes more sense, and I think it would be clearer if it were referred to as such in the instructions.

### Additional Context

I paired with a Technical Coach who agreed that this seemed like a typo in the instructions, and suggested I flag the issue here. 

### Suggested Changes

Just a typo change--changing "post" to "posts" in the instructions would suffice, I think!

**Comment by lizbur10** [comment]
Hi @IguanasEverywhere ! Thanks for submitting this feedback. The correction has now been made.

Thanks for contributing to the Flatiron School curriculum 💙
