### ISSUE TITLE
Please Consider Renaming 'Article' And 'ArticleList' To 'Post' And 'PostList'

### ISSUE THREAD

**Issue by SamuelBanya** [learn-co-curriculum/react-hooks-component-props-mini-project#8]
### Canvas Link

https://learning.flatironschool.com/courses/5285/assignments/172447?module_item_id=376309

### Concern

The following should be revised for this lesson:
'Article' and 'ArticleList' components should be renamed to 'Post' and 'PostList'.

This is because this is a blog website with posts, and not academic articles. The context with the naming is weird, and would be easier if this was just renamed accordingly.

### Suggested Changes

Mentioned above ^

**Comment by lizbur10** [comment]
Hi @SamuelBanya ! Thank you for bringing this to our attention. I have made a note of your feedback and we will consider implementing it when this lesson is next updated.

Thanks for contributing to the Flatiron School curriculum 💙
